### ISSUE TITLE
using fixed pathes in script breaks strato vserver install 

### ISSUE THREAD

**Issue by roadrunnerjb** [criegerde/nextcloud-installationsskripte#1]
Hi,

erst Mal Danke für das script. Ich habe das heute in einem frisch aufgesetzten Strato V-Server mit Ubuntu  20.04.3 LTS ausprobiert.
Dabei sind mir einige Fehlermeldungen bzgl. der verwendeten Tools sed, rm, cat, tar, echo, ... aufgefallen:

```
...
./install.sh: line 676: /usr/bin/rm: No such file or directory
./install.sh: line 680: /usr/bin/cat: No such file or directory
...

```

Ich sehe dass diese im script explizit mit /usr/bin/<tool> angesprochen werden. Wenn ich aber das Betriebssystem frage wo die Tools zu finden sind, liegen die woanders:

```
root@........:/nextcloud-installation# which sed
/bin/sed

```

Eine Optimierung des scripts könnte sein die Tools über Variablen anzusprechen und den Inhalt der Variablen über which zu bestimmen:

```
sed=$(which sed)
${sed} ...

```
so könnten die genutzten Tools auch zu Beginn abgefragt werden.

Mein Problem ist nun, dass manche Schritte in den Script gelaufen sind, andere dagegen nicht weitere die auf vorangegangenes aufbauen dann nicht geklappt haben. Die Analyse festzustellen weas geklappt hat und was nicht ist jetz leider aufwändig... Idee dazu ?

Gruß
Joachim

**Comment by criegerde** [comment]
Systempfade werden ausgelesen und verwendet
