### ISSUE TITLE
Maybe error during install? 

### ISSUE THREAD

**Issue by dffvb** [criegerde/nextcloud-installationsskripte#2]
Hi there, 

used this script succefully multiple times in the past. Many thanks (already doanted). Now it sometimes throws an error at the end of the installation script, right after

"- Command may disrupt existing ssh connections. Proceed with operation (y|n)? <Y> + |ENTER|"

"Nextcloud is not installed - only a limited number of commands are available"
                                                                                                                        
" Command "app:disable" is not defined.  "

"Do you want to run "app:check-code" instead?  (yes/no) [no]:"

Regardless of what you answer (yes or no), after a few attemps it finishes the process. 

If you then enter the IP of the nextcloud it gives you this window where you can enter admin, database, db name etc. if you enter the same values you entered before during the script, it tells you the user already exists... if you enter a new user, it tells me to change the directory 0770…. 

Had this on Ubuntu Server 20.04.2 LTS - Hyper-V and KVM.

I have a suspection, which might resolves it: 

I think I had this when entering as data path /media
When entering /home/data it worked
For testing I tried to mount an NFS share to /home/data and install there, got the error again... 

Any help appreciated.

**Comment by criegerde** [comment]
Your description points to earlier problems while the scripts was running (php / database failures?).
Please have a look at your install.log to fix these errors.

First remove the installed software:

apt remove --purge nginx* php* mariadb* redis*
rm -Rf /var/www etc/php /etc/mysql/my.cnf /nextcloud-installation/install.log

Second, re-run the script.
./install.sh
